version: '3'
services:
  es0:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es0
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - node.name=es0
      - cluster.name=demo
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es0,es1,es2
      - discovery.seed_hosts=es1,es2
      - ELASTIC_PASSWORD=thisisatest
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es0-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - "9200"

  es1:
    depends_on:
      - es0
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es1
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - node.name=es1
      - cluster.name=demo
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es0,es1,es2
      - discovery.seed_hosts=es0,es2
      - ELASTIC_PASSWORD=thisisatest
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es1-data:/usr/share/elasticsearch/data

  es2:
    depends_on:
      - es1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: es2
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      - node.name=es2
      - cluster.name=demo
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es0,es1,es2
      - discovery.seed_hosts=es0,es1
      - ELASTIC_PASSWORD=thisisatest
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es2-data:/usr/share/elasticsearch/data

volumes:
  es0-data:
    driver: local
  es1-data:
    driver: local
  es2-data:
    driver: local
